- name: Locate the MapReduce examples jar
  shell: "find $(which hadoop|awk -F 'bin/hadoop' '{print $1}') -name 'hadoop-mapreduce-examples.jar' -print -quit"
  register: examples_jar

- name: Run pi MapReduce example
  shell: "yarn jar {{ examples_jar.stdout }} pi 8 1000"
  register: pi_result 

- name: Debug pi example job result
  debug:
    var: pi_result.stdout
      

